# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Project
mod_version=26.1-r2.2
project_group=net.rebel459.item_tooltips
license=LGPL 3.0-Only
java_version=25

# Mod
mod_author=Rebel459
mod_id=item_tooltips
mod_name=Item Tooltips
mod_description=A highly configurable item descriptions, enchantment descriptions and tooltip wrapping mod.

# Minecraft
minecraft_version=26.1
neo_form_version=26.1-1

# Fabric
fabric_loader=0.18.5
fabric_api=0.144.0+26.1
fabric_minecraft_version=>=26.1 <26.2

# NeoForge
neoforge_version=26.1.0.1-beta
neoforge_minecraft_version=[26.1, 26.2)

# Common Dependencies
unified_version=26.1-r3.0
cloth_version=26.1.154

# Fabric Dependencies
modmenu_version=18.0.0-alpha.8
jei_version=5QFemzpl