# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Project
mod_version=26.2-r1.0
project_group=net.rebel459.item_tooltips
license=LGPL 3.0-Only
java_version=25

# Mod
mod_author=Rebel459
mod_id=item_tooltips
mod_name=Item Tooltips
mod_description=A highly configurable item descriptions, enchantment descriptions and tooltip wrapping mod.

# Minecraft
minecraft_version=26.2
neo_form_version=26.2-1

# Fabric
fabric_loader=0.19.3
fabric_api=0.156.0+26.2
fabric_minecraft_version=>=26.2 <26.3

# NeoForge
neoforge_version=26.2.0.45-beta
neoforge_minecraft_version=[26.2, 26.3)

# Common Dependencies
unified_version=26.2-r1.0
cloth_version=26.2.155

# Fabric Dependencies
modmenu_version=20.0.1
jei_version=X7rXLCVM